[package]
name = "memcpy"
version = "0.1.0"
authors = ["Simon Génier <simon.genier@umontreal.ca>"]
edition = "2018"

[[bench]]
name = "memcpy"
harness = false

[dev-dependencies.bytesize]
version = "1.0"

[dev-dependencies.criterion]
version = "0.3"

[dev-dependencies.memmap]
version = "0.7.0"
